@startuml
class Board {
    - Map<Integer, Tile> tiles
    - int rows, collums
    - BoardType boardType
    + void addTile(Tile tile)
    + Map<Integer, Tile> getTiles()
    + int calculateTileId(int row, int collum)

}
@enduml